# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:01:24+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, constr


class Amount(BaseModel):
    currency: constr(min_length=3, max_length=3) = Field(
        ...,
        description='The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes).',
    )
    value: int = Field(
        ...,
        description='The amount of the transaction, in [minor units](https://docs.adyen.com/development-resources/currency-codes).',
    )


class BinDetail(BaseModel):
    issuerCountry: Optional[str] = Field(
        None, description='The country where the card was issued.'
    )


class CardBin(BaseModel):
    bin: Optional[str] = Field(
        None,
        description='The first 6 digit of the card number. Enable this field via merchant account settings.',
    )
    commercial: Optional[bool] = Field(
        None,
        description='If true, it indicates a commercial card. Enable this field via merchant account settings.',
    )
    fundingSource: Optional[str] = Field(
        None,
        description='The card funding source. Valid values are:\n* CHARGE\n* CREDIT\n* DEBIT\n* DEFERRED_DEBIT\n* PREPAID\n* PREPAID_RELOADABLE\n* PREPAID_NONRELOADABLE\n> Enable this field via merchant account settings.',
    )
    fundsAvailability: Optional[str] = Field(
        None,
        description='Indicates availability of funds.\n\nVisa:\n* "I" (fast funds are supported)\n* "N" (otherwise)\n\nMastercard:\n* "I" (product type is Prepaid or Debit, or issuing country is in CEE/HGEM list)\n* "N" (otherwise)\n> Returned when you verify a card BIN or estimate costs, and only if `payoutEligible` is different from "N" or "U".',
    )
    issuerBin: Optional[str] = Field(
        None,
        description='The first 8 digit of the card number. Enable this field via merchant account settings.',
    )
    issuingBank: Optional[str] = Field(
        None, description='The issuing bank of the card.'
    )
    issuingCountry: Optional[str] = Field(
        None, description='The country where the card was issued from.'
    )
    issuingCurrency: Optional[str] = Field(
        None, description='The currency of the card.'
    )
    paymentMethod: Optional[str] = Field(
        None,
        description='The payment method associated with the card (e.g. visa, mc, or amex).',
    )
    payoutEligible: Optional[str] = Field(
        None,
        description='Indicates whether a payout is eligible or not for this card.\n\nVisa:\n* "Y"\n* "N"\n\nMastercard:\n* "Y" (domestic and cross-border)\n* "D" (only domestic)\n* "N" (no MoneySend)\n* "U" (unknown)\n> Returned when you verify a card BIN or estimate costs, and only if `payoutEligible` is different from "N" or "U".',
    )
    summary: Optional[str] = Field(
        None, description='The last four digits of the card number.'
    )


class CostEstimateAssumptions(BaseModel):
    assume3DSecureAuthenticated: Optional[bool] = Field(
        None,
        description='If true, the cardholder is expected to successfully authorise via 3D Secure.',
    )
    assumeLevel3Data: Optional[bool] = Field(
        None,
        description='If true, the transaction is expected to have valid Level 3 data.',
    )
    installments: Optional[int] = Field(
        None, description='If not zero, the number of installments.'
    )


class ShopperInteraction(Enum):
    Ecommerce = 'Ecommerce'
    ContAuth = 'ContAuth'
    Moto = 'Moto'
    POS = 'POS'


class CostEstimateResponse(BaseModel):
    cardBin: Optional[CardBin] = Field(None, description='Card BIN details.')
    costEstimateAmount: Optional[Amount] = Field(
        None,
        description='The estimated cost (scheme fee + interchange) in the settlement currency. If the settlement currency cannot be determined, the fee in EUR is returned.',
    )
    costEstimateReference: Optional[str] = Field(
        None, description="Adyen's 16-character reference associated with the request."
    )
    resultCode: Optional[str] = Field(
        None, description='The result of the cost estimation.'
    )
    surchargeType: Optional[str] = Field(
        None,
        description='Indicates the way the charges can be passed on to the cardholder. The following values are possible:\n* `ZERO` - the charges are not allowed to pass on\n* `PASSTHROUGH` - the charges can be passed on\n* `UNLIMITED` - there is no limit on how much surcharge is passed on',
    )


class DSPublicKeyDetail(BaseModel):
    brand: Optional[str] = Field(None, description='Card brand.')
    directoryServerId: Optional[str] = Field(
        None, description='Directory Server (DS) identifier.'
    )
    fromSDKVersion: Optional[str] = Field(
        None,
        description='The version of the mobile 3D Secure 2 SDK. For the possible values, refer to the versions in [Adyen 3DS2 Android](https://github.com/Adyen/adyen-3ds2-android/releases) and [Adyen 3DS2 iOS](https://github.com/Adyen/adyen-3ds2-ios/releases).',
    )
    publicKey: Optional[str] = Field(
        None,
        description='Public key. The 3D Secure 2 SDK encrypts the device information by using the DS public key.',
    )


class MerchantDetails(BaseModel):
    countryCode: Optional[constr(min_length=2, max_length=2)] = Field(
        None,
        description="2-letter ISO 3166 country code of the card acceptor location.\n> This parameter is required for the merchants who don't use Adyen as the payment authorisation gateway.",
    )
    enrolledIn3DSecure: Optional[bool] = Field(
        None,
        description='If true, indicates that the merchant is enrolled in 3D Secure for the card network.',
    )
    mcc: Optional[str] = Field(
        None,
        description='The merchant category code (MCC) is a four-digit number which relates to a particular market segment. This code reflects the predominant activity that is conducted by the merchant.\n\nThe list of MCCs can be found [here](https://en.wikipedia.org/wiki/Merchant_category_code).',
    )


class Contract(Enum):
    ONECLICK = 'ONECLICK'
    RECURRING = 'RECURRING'
    PAYOUT = 'PAYOUT'


class TokenService(Enum):
    VISATOKENSERVICE = 'VISATOKENSERVICE'
    MCTOKENSERVICE = 'MCTOKENSERVICE'


class Recurring(BaseModel):
    contract: Optional[Contract] = Field(
        None,
        description='The type of recurring contract to be used.\nPossible values:\n* `ONECLICK` – Payment details can be used to initiate a one-click payment, where the shopper enters the [card security code (CVC/CVV)](https://docs.adyen.com/payments-fundamentals/payment-glossary#card-security-code-cvc-cvv-cid).\n* `RECURRING` – Payment details can be used without the card security code to initiate [card-not-present transactions](https://docs.adyen.com/payments-fundamentals/payment-glossary#card-not-present-cnp).\n* `ONECLICK,RECURRING` – Payment details can be used regardless of whether the shopper is on your site or not.\n* `PAYOUT` – Payment details can be used to [make a payout](https://docs.adyen.com/online-payments/online-payouts).',
    )
    recurringDetailName: Optional[str] = Field(
        None, description='A descriptive name for this detail.'
    )
    recurringExpiry: Optional[datetime] = Field(
        None,
        description='Date after which no further authorisations shall be performed. Only for 3D Secure 2.',
    )
    recurringFrequency: Optional[str] = Field(
        None,
        description='Minimum number of days between authorisations. Only for 3D Secure 2.',
    )
    tokenService: Optional[TokenService] = Field(
        None, description='The name of the token service.'
    )


class ServiceError(BaseModel):
    additionalData: Optional[Dict[str, str]] = Field(
        None,
        description='Contains additional information about the payment. Some data fields are included only if you select them first. Go to **Customer Area** > **Developers** > **Additional data**.',
    )
    errorCode: Optional[str] = Field(
        None, description='The error code mapped to the error message.'
    )
    errorType: Optional[str] = Field(None, description='The category of the error.')
    message: Optional[str] = Field(
        None, description='A short explanation of the issue.'
    )
    pspReference: Optional[str] = Field(
        None, description='The PSP reference of the payment.'
    )
    status: Optional[int] = Field(None, description='The HTTP response status.')


class ThreeDS2CardRangeDetail(BaseModel):
    acsInfoInd: Optional[List[str]] = Field(
        None,
        description='Provides additional information to the 3DS Server.\nPossible values:\n- 01 (Authentication is available at ACS)\n- 02 (Attempts supported by ACS or DS)\n- 03 (Decoupled authentication supported)\n- 04 (Whitelisting supported)',
    )
    brandCode: Optional[str] = Field(None, description='Card brand.')
    endRange: Optional[str] = Field(None, description='BIN end range.')
    startRange: Optional[str] = Field(None, description='BIN start range.')
    threeDS2Versions: Optional[List[str]] = Field(
        None, description='Supported 3D Secure protocol versions'
    )
    threeDSMethodURL: Optional[str] = Field(
        None,
        description='In a 3D Secure 2 browser-based flow, this is the URL where you should send the device fingerprint to.',
    )


class ThreeDSAvailabilityRequest(BaseModel):
    additionalData: Optional[Dict[str, str]] = Field(
        None,
        description='This field contains additional data, which may be required for a particular request.\n\nThe `additionalData` object consists of entries, each of which includes the key and value.',
    )
    brands: Optional[List[str]] = Field(None, description='List of brands.')
    cardNumber: Optional[str] = Field(None, description='Card number or BIN.')
    merchantAccount: str = Field(..., description='The merchant account identifier.')
    recurringDetailReference: Optional[str] = Field(
        None, description='A recurring detail reference corresponding to a card.'
    )
    shopperReference: Optional[str] = Field(
        None,
        description="The shopper's reference to uniquely identify this shopper (e.g. user ID or account ID).",
    )


class ThreeDSAvailabilityResponse(BaseModel):
    binDetails: Optional[BinDetail] = Field(None, description='Bin Group Details')
    dsPublicKeys: Optional[List[DSPublicKeyDetail]] = Field(
        None, description='List of Directory Server (DS) public keys.'
    )
    threeDS1Supported: Optional[bool] = Field(
        None, description='Indicator if 3D Secure 1 is supported.'
    )
    threeDS2CardRangeDetails: Optional[List[ThreeDS2CardRangeDetail]] = Field(
        None, description='List of brand and card range pairs.'
    )
    threeDS2supported: Optional[bool] = Field(
        None, description='Indicator if 3D Secure 2 is supported.'
    )


class CostEstimateRequest(BaseModel):
    amount: Amount = Field(
        ...,
        description='The transaction amount used as a base for the cost estimation.',
    )
    assumptions: Optional[CostEstimateAssumptions] = Field(
        None,
        description='Assumptions made for the expected characteristics of the transaction, for which the charges are being estimated.',
    )
    cardNumber: Optional[constr(min_length=4, max_length=19)] = Field(
        None,
        description='The card number (4-19 characters) for PCI compliant use cases. Do not use any separators.\n\n> Either the `cardNumber` or `encryptedCardNumber` field must be provided in a payment request.',
    )
    encryptedCardNumber: Optional[str] = Field(
        None,
        description='Encrypted data that stores card information for non PCI-compliant use cases. The encrypted data must be created with the Checkout Card Component or Secured Fields Component, and must contain the `encryptedCardNumber` field.\n\n> Either the `cardNumber` or `encryptedCardNumber` field must be provided in a payment request.',
    )
    merchantAccount: str = Field(
        ...,
        description='The merchant account identifier you want to process the (transaction) request with.',
    )
    merchantDetails: Optional[MerchantDetails] = Field(
        None,
        description="Additional data for merchants who don't use Adyen as the payment authorisation gateway.",
    )
    recurring: Optional[Recurring] = Field(
        None,
        description='The recurring settings for the payment. Use this property when you want to enable [recurring payments](https://docs.adyen.com/online-payments/tokenization).',
    )
    selectedRecurringDetailReference: Optional[str] = Field(
        None,
        description='The `recurringDetailReference` you want to use for this cost estimate. The value `LATEST` can be used to select the most recently stored recurring detail.',
    )
    shopperInteraction: Optional[ShopperInteraction] = Field(
        None,
        description='Specifies the sales channel, through which the shopper gives their card details, and whether the shopper is a returning customer.\nFor the web service API, Adyen assumes Ecommerce shopper interaction by default.\n\nThis field has the following possible values:\n* `Ecommerce` - Online transactions where the cardholder is present (online). For better authorisation rates, we recommend sending the card security code (CSC) along with the request.\n* `ContAuth` - Card on file and/or subscription transactions, where the card holder is known to the merchant (returning customer). If the shopper is present (online), you can supply also the CSC to improve authorisation (one-click payment).\n* `Moto` - Mail-order and telephone-order transactions where the shopper is in contact with the merchant via email or telephone.\n* `POS` - Point-of-sale transactions where the shopper is physically present to make a payment using a secure payment terminal.',
    )
    shopperReference: Optional[str] = Field(
        None,
        description='Required for recurring payments. \nYour reference to uniquely identify this shopper, for example user ID or account ID. Minimum length: 3 characters.\n> Your reference must not include personally identifiable information (PII), for example name or email address.',
    )
